CREATE TABLE modelo (
    codigo BIGINT(20) PRIMARY KEY AUTO_INCREMENT,
    nome VARCHAR(50) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE veiculo (
    codigo BIGINT(20) PRIMARY KEY AUTO_INCREMENT,  
    placa VARCHAR(80) NOT NULL,    
    codigo_modelo BIGINT(20) NOT NULL,
    FOREIGN KEY (codigo_modelo) REFERENCES modelo(codigo)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

INSERT INTO modelo VALUES (0, 'Carreta');
INSERT INTO modelo VALUES (0, 'Truck');